### ISSUE TITLE
Game hangs when trying to save

### ISSUE THREAD

**Issue by EricOakford** [Kawa-oneechan/SCI11-Plus#4]
When attempting to save games, the interpreter hangs without ever bringing up the save/restore dialog. This does not happen in the original interpreter, so it's not an issue with any scripts. Strangely, the restore dialog works fine. I'm using a build from the BASE source.

**Comment by Kawa-oneechan** [comment]
Can confirm this happens on both BASE and EXT. I'll do some digging in history.

**Comment by Kawa-oneechan** [comment]
If you can confirm this fixes it...

**Comment by EricOakford** [comment]
Yes, it seems to work okay now. Will update the interpreter in my SCI1.1 template.

**Comment by Kawa-oneechan** [comment]
Ohoh, *that's* what you're using the base build for? Feels good, man.
